<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="renderer" content="webkit">
<meta http-equiv="Cache-Control" content="no-siteapp" />
<title><?php if (isset($title)) {echo $title;}else{ echo ""; }?></title>

<meta name="keywords" content="<?php if (isset($keywords)) {echo $keywords;}else{ echo ""; }?>">
<meta name="description" content="<?php if (isset($description)) {echo $description;}else{ echo ""; }?>">

<!--[if lt IE 8]>
<meta http-equiv="refresh" content="0;ie.html" />
<![endif]-->

<link rel="shortcut icon" href="/favicon.ico">
<link href="/public/css/bootstrap.min.css?v=3.3.5" rel="stylesheet">
<link href="/public/css/font-awesome.min.css?v=4.4.0" rel="stylesheet">



