<!--左侧导航开始-->
<nav class="navbar-default navbar-static-side" role="navigation">
    <div class="nav-close"><i class="fa fa-times-circle"></i>
    </div>
    <div class="sidebar-collapse">
        <ul class="nav" id="side-menu">
            <li class="nav-header">
                <div class="dropdown profile-element">
                    <span><img alt="image" class="img-circle" src="/public/img/profile_small.jpg" /></span>
                    <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                                <span class="clear">
                               <span class="block m-t-xs"><strong class="font-bold">Beaut-zihan</strong></span>
                                <span class="text-muted text-xs block">超级管理员<b class="caret"></b></span>
                                </span>
                    </a>
                    <ul class="dropdown-menu animated fadeInRight m-t-xs">
                        <li><a class="J_menuItem" href="form_avatar.html">修改头像</a>
                        </li>
                        <li><a class="J_menuItem" href="profile.html">个人资料</a>
                        </li>
                        <li><a class="J_menuItem" href="contacts.html">联系我们</a>
                        </li>
                        <li><a class="J_menuItem" href="mailbox.html">信箱</a>
                        </li>
                        <li class="divider"></li>
                        <li><a href="login.html">安全退出</a>
                        </li>
                    </ul>
                </div>
                <div class="logo-element">H+
                </div>
            </li>

            <li>
                <a href="#"><i class="fa fa-desktop"></i> <span class="nav-label">用户中心</span><span class="fa arrow"></span></a>
                <ul class="nav nav-second-level">

                    <li><a class="J_menuItem" href="profile.html">用户信息编辑</a>
                    </li>
                    <li><a class="J_menuItem" href="contacts.html">用户等级</a>
                    </li>

                    <li>
                        <a href="#">用户登录 <span class="fa arrow"></span></a>
                        <ul class="nav nav-third-level">
                            <li><a class="J_menuItem" href="projects.html">微信登陆</a>
                            </li>
                            <li><a class="J_menuItem" href="project_detail.html">本平台登录</a>
                            </li>
                        </ul>
                    </li>
                    <li><a class="J_menuItem" href="contacts.html">申请实体卡</a>
                    </li>
                    <li><a class="J_menuItem" href="contacts.html">绑定实体卡</a>
                    </li>
                    <li><a class="J_menuItem" href="contacts.html">修改密码</a>
                    </li>
                    <li><a class="J_menuItem" href="contacts.html">忘记密码</a>
                    </li>
                    <li><a class="J_menuItem" href="contacts.html">退出登录</a>
                    </li>
                    <li><a class="J_menuItem" href="contacts.html">我的购物车</a>
                    </li>
                    <li><a class="J_menuItem" href="contacts.html">我的订单</a>
                    </li>
                    <li><a class="J_menuItem" href="contacts.html">我的收藏</a>
                    </li>
                    <li><a class="J_menuItem" href="contacts.html">我的分享</a>
                    </li>
                    <li><a class="J_menuItem" href="contacts.html">我的消息</a>
                    </li>
                    <li><a class="J_menuItem" href="contacts.html">我的评价</a>
                    </li>
                    <li><a class="J_menuItem" href="contacts.html">收货地址</a>
                    </li>
                    <li><a class="J_menuItem" href="contacts.html">服务呼叫</a>
                    </li>
                    <li><a class="J_menuItem" href="contacts.html">我的预约</a>
                    </li>
                    <li><a class="J_menuItem" href="contacts.html">签到</a>
                    </li>
                    <li>
                        <a href="#">我的记录 <span class="fa arrow"></span></a>
                        <ul class="nav nav-third-level">
                            <li><a class="J_menuItem" href="projects.html">积分收入</a>
                            </li>
                            <li><a class="J_menuItem" href="project_detail.html">积分支出</a>
                            </li>
                            <li><a class="J_menuItem" href="project_detail.html">签到</a>
                            </li>
                            <li><a class="J_menuItem" href="project_detail.html">余额消费</a>
                            </li>
                            <li><a class="J_menuItem" href="project_detail.html">余额充值</a>
                            </li>
                        </ul>
                    </li>
                    <li><a class="J_menuItem" href="contacts.html">积分显示</a>
                    </li>
                    <li><a class="J_menuItem" href="contacts.html">余额显示</a>
                    </li>
                    <li><a class="J_menuItem" href="contacts.html">余额充值</a>
                    </li>

                </ul>
            </li>
            <li>
                <a href="#"><i class="fa fa-desktop"></i> <span class="nav-label">线上商城</span><span class="fa arrow"></span></a>
                <ul class="nav nav-second-level">
                    <li><a class="J_menuItem" href="contacts.html">商品分类</a>
                    </li>
                    <li><a class="J_menuItem" href="profile.html">商品动态属性</a>
                    </li>
                    <li><a class="J_menuItem" href="contacts.html">积分兑换</a>
                    </li>
                    <li><a class="J_menuItem" href="profile.html">团购</a>
                    </li>
                    <li><a class="J_menuItem" href="contacts.html">抢购</a>
                    </li>
                    <li>
                        <a href="#">商品信息添加 <span class="fa arrow"></span></a>
                        <ul class="nav nav-third-level">
                            <li><a class="J_menuItem" href="projects.html">商户商品</a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </li>
            <li>
                <a href="#"><i class="fa fa-desktop"></i> <span class="nav-label">物业服务</span><span class="fa arrow"></span></a>
                <ul class="nav nav-second-level">
                    <li><a class="J_menuItem" href="contacts.html">提交服务</a>
                    </li>
                    <li><a class="J_menuItem" href="profile.html">服务类目</a>
                    </li>
                    <li><a class="J_menuItem" href="contacts.html">一级分类</a>
                    </li>
                    <li><a class="J_menuItem" href="profile.html">二级分类</a>
                    </li>
                    <li><a class="J_menuItem" href="contacts.html">服务详情介绍</a>
                    </li>
                    <li><a class="J_menuItem" href="profile.html">图片</a>
                    </li>
                    <li><a class="J_menuItem" href="contacts.html">收藏</a>
                    </li>
                    <li><a class="J_menuItem" href="profile.html">分享</a>
                    </li>

                </ul>
            </li>
            <li>
                <a href="#"><i class="fa fa-desktop"></i> <span class="nav-label">家政服务</span><span class="fa arrow"></span></a>
                <ul class="nav nav-second-level">
                    <li><a class="J_menuItem" href="contacts.html">提交服务</a>
                    </li>
                    <li><a class="J_menuItem" href="profile.html">服务类目</a>
                    </li>
                    <li><a class="J_menuItem" href="contacts.html">一级分类</a>
                    </li>
                    <li><a class="J_menuItem" href="profile.html">二级分类</a>
                    </li>
                    <li><a class="J_menuItem" href="contacts.html">服务详情介绍</a>
                    </li>
                    <li><a class="J_menuItem" href="profile.html">图片</a>
                    </li>
                    <li><a class="J_menuItem" href="contacts.html">收藏</a>
                    </li>
                    <li><a class="J_menuItem" href="profile.html">分享</a>
                    </li>
                </ul>
            </li>
            <li>
                <a href="#"><i class="fa fa-desktop"></i> <span class="nav-label">居家养老</span><span class="fa arrow"></span></a>
                <ul class="nav nav-second-level">
                    <li><a class="J_menuItem" href="contacts.html">简介</a>
                    </li>
                    <li><a class="J_menuItem" href="profile.html">客服</a>
                    </li>
                    <li>
                        <a href="#">服务板块<span class="fa arrow"></span></a>
                        <ul class="nav nav-third-level">
                            <li><a class="J_menuItem" href="projects.html">一级分类</a>
                            </li>
                            <li><a class="J_menuItem" href="project_detail.html">二级分类</a>
                            </li>
                            <li><a class="J_menuItem" href="project_detail.html">详情</a>
                            </li>
                            <li><a class="J_menuItem" href="project_detail.html">图片</a>
                            </li>
                            <li><a class="J_menuItem" href="project_detail.html">收藏</a>
                            </li>
                            <li><a class="J_menuItem" href="project_detail.html">分享</a>
                            </li>
                        </ul>
                    </li>
                    <li><a class="J_menuItem" href="profile.html">新闻板块</a>
                    </li>
                    <li><a class="J_menuItem" href="profile.html">建议反馈</a>
                    </li>

                </ul>
            </li>
            <li>
                <a href="#"><i class="fa fa-desktop"></i> <span class="nav-label">特惠商户</span><span class="fa arrow"></span></a>
                <ul class="nav nav-second-level">
                    <li><a class="J_menuItem" href="contacts.html">商户注册</a>
                    </li>
                    <li><a class="J_menuItem" href="profile.html">需要合同</a>
                    </li>
                    <li><a class="J_menuItem" href="profile.html">证书等资料</a>
                    </li>
                    <li><a class="J_menuItem" href="profile.html">商户信息</a>
                    </li>
                    <li><a class="J_menuItem" href="profile.html">广告图片</a>
                    </li>
                    <li><a class="J_menuItem" href="profile.html">详情</a>
                    </li>
                    <li><a class="J_menuItem" href="profile.html">收藏</a>
                    </li>
                    <li><a class="J_menuItem" href="profile.html">分享</a>
                    </li>

                </ul>
            </li>
            <li>
                <a href="#"><i class="fa fa-desktop"></i> <span class="nav-label">生活百事通</span><span class="fa arrow"></span></a>
                <ul class="nav nav-second-level">
                    <li><a class="J_menuItem" href="contacts.html">联系我们</a>
                    </li>
                    <li><a class="J_menuItem" href="profile.html">广告图</a>
                    </li>
                    <li><a class="J_menuItem" href="profile.html">添加链接</a>
                    </li>
                    <li><a class="J_menuItem" href="profile.html">信息</a>
                    </li>

                </ul>
            </li>

            <li>
                <a href="#"><i class="fa fa-desktop"></i> <span class="nav-label">自主缴费</span><span class="fa arrow"></span></a>
                <ul class="nav nav-second-level">
                    <li><a class="J_menuItem" href="contacts.html">物业</a>
                    </li>
                    <li><a class="J_menuItem" href="profile.html">水</a>
                    </li>
                    <li><a class="J_menuItem" href="contacts.html">电</a>
                    </li>
                    <li><a class="J_menuItem" href="profile.html">取暖费</a>
                    </li>
                    <li><a class="J_menuItem" href="contacts.html">手机费</a>
                    </li>
                    <li><a class="J_menuItem" href="profile.html">电话费</a>
                    </li>
                    <li><a class="J_menuItem" href="profile.html">宽带费</a>
                    </li>

                </ul>
            </li>
            <li>
                <a href="#"><i class="fa fa-desktop"></i> <span class="nav-label">二手市场</span><span class="fa arrow"></span></a>
                <ul class="nav nav-second-level">
                    <li><a class="J_menuItem" href="contacts.html">二手类目</a>
                    </li>
                    <li><a class="J_menuItem" href="profile.html">分类</a>
                    </li>
                    <li><a class="J_menuItem" href="contacts.html">广告</a>
                    </li>
                    <li><a class="J_menuItem" href="profile.html">信息</a>
                    </li>


                </ul>
            </li>

        </ul>
    </div>
</nav>
<!--左侧导航结束-->